# Generated by Django 5.2.15 on 2026-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('weapon_type', models.CharField(choices=[('Espada', 'Espada'), ('Espadão', 'Espadão'), ('Arco', 'Arco'), ('Lança', 'Lança'), ('Manopla', 'Manopla'), ('Tomo', 'Tomo'), ('Varinha', 'Varinha')], max_length=20, verbose_name='Tipo')),
                ('rarity', models.CharField(choices=[('Comum', 'Comum'), ('Incomum', 'Incomum'), ('Rara', 'Rara'), ('Lendária', 'Lendária'), ('Mítica', 'Mítica'), ('Iluminada', 'Iluminada')], default='Comum', max_length=20, verbose_name='Raridade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapons/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ['name'],
            },
        ),
    ]
