# Generated by Django 5.2.15 on 2026-07-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factions', '0001_initial'),
        ('kingdoms', '0001_initial'),
        ('spells', '0001_initial'),
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('age', models.PositiveIntegerField(verbose_name='Idade')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20, verbose_name='Gênero')),
                ('race', models.CharField(max_length=100, verbose_name='Raça')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura')),
                ('character_type', models.CharField(choices=[('Flama', 'Flama'), ('Aqua', 'Aqua'), ('Terrae', 'Terrae'), ('Eol', 'Eol'), ('Crelix', 'Crelix'), ('Fulmen', 'Fulmen'), ('Lux', 'Lux'), ('Umbra', 'Umbra'), ('Vita', 'Vita'), ('Toxi', 'Toxi'), ('Vis', 'Vis'), ('Inzurvitus', 'Inzurvitus')], max_length=20, verbose_name='Tipagem')),
                ('personality', models.TextField(verbose_name='Personalidade')),
                ('history', models.TextField(verbose_name='História')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='factions.faction', verbose_name='Facção')),
                ('kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='kingdoms.kingdom', verbose_name='Reino')),
                ('spells', models.ManyToManyField(blank=True, related_name='characters', to='spells.spell', verbose_name='Magias')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='weapons.weapon', verbose_name='Arma Principal')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['name'],
            },
        ),
    ]
