# Generated by Django 5.2.15 on 2026-07-05 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_migrate_race_data'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='races.race', verbose_name='Raça'),
        ),
    ]
