# Generated by Django 5.2.15 on 2026-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_race_fk_alter_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='history',
            field=models.TextField(blank=True, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, verbose_name='Personalidade'),
        ),
    ]
