# Generated by Django 5.2.15 on 2026-07-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('Ativa', 'Ativa'), ('Passiva', 'Passiva'), ('Suprema', 'Suprema')], max_length=20, verbose_name='Categoria')),
                ('spell_type', models.CharField(choices=[('Flama', 'Flama'), ('Aqua', 'Aqua'), ('Terrae', 'Terrae'), ('Eol', 'Eol'), ('Crelix', 'Crelix'), ('Fulmen', 'Fulmen'), ('Lux', 'Lux'), ('Umbra', 'Umbra'), ('Vita', 'Vita'), ('Toxi', 'Toxi'), ('Vis', 'Vis')], max_length=20, verbose_name='Tipagem')),
                ('function', models.CharField(max_length=100, verbose_name='Função')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spells/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magia',
                'verbose_name_plural': 'Magias',
                'ordering': ['name'],
            },
        ),
    ]
