# Generated by Django 5.2.15 on 2026-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='kingdoms/banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='color',
            field=models.CharField(default='#d8b35f', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='history',
            field=models.TextField(blank=True, verbose_name='História'),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título'),
        ),
    ]
