# Generated by Django 5.2.15 on 2026-07-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kingdoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('leader', models.CharField(max_length=100, verbose_name='Líder')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='factions/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='kingdoms.kingdom', verbose_name='Reino')),
            ],
            options={
                'verbose_name': 'Facção',
                'verbose_name_plural': 'Facções',
                'ordering': ['name'],
            },
        ),
    ]
